// Quadratisches Spielfeld = ganzes Hintergrundbild sichtbar (füllt Tablet/PC groß).
export const VIRTUAL_W = 900;
export const VIRTUAL_H = 900;
export const PLAYER_SPEED = 340; // virtuelle Pixel pro Sekunde
export const RARITIES = ["common", "uncommon", "rare"];
export const EASE = { common: 1.0, uncommon: 0.75, rare: 0.55 };
// Kleiner grüner Zielbereich (Bruchteil der Leiste). Treffen = gefangen, sonst nicht.
// Seltenere Pokémon = kleinerer Bereich. Position wird pro Begegnung zufällig gesetzt.
export const GREEN_ZONE = { common: 0.16, uncommon: 0.11, rare: 0.07 };
export const MAX_PER_SPECIES = 5; // 5x fangen -> Sprite wird golden, taucht nicht mehr auf
export const BOSS_ID = 11;         // Lukas, erscheint wenn alle 10 Arten golden sind
export const BOSS_BAND = 0.09;     // Bandgröße beim Boss (beide Balken bewegen sich)
export const SPAWN_WEIGHT = { common: 5, uncommon: 3, rare: 1.5 };
export const MAX_ACTIVE_SPAWNS = 2;
export const SPAWN_INTERVAL = 2.5; // Sekunden zwischen Spawn-Versuchen
export const GRASS_HIT_RADIUS = 82; // virtuelle Pixel
export const POWERBAR_PERIOD = 2.6; // Standard/Boss-Marker-Tempo (Sekunden je Hoch-Runter-Zyklus)
// Marker-Tempo je Seltenheit: häufig langsam (leicht), selten etwas schneller (schwerer) – aber kindgerecht
export const PERIOD_BY_RARITY = { common: 2.8, uncommon: 2.5, rare: 2.2 };
